import { Suspense } from 'react';
import './globals.css';
import Loading from './loading';
import SearchBarController from './SearchBarController';
import Provider from './lib/react-query/Provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="flex h-full w-full flex-col bg-sky-200">
            <Suspense fallback={<Loading />}>
              <SearchBarController />
            </Suspense>
            <div className="h-full flex-grow">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
